name: streamshop
version: 1.0.0
config-version: 2

profile: streamshop

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

models:
  streamshop:
    staging:
      +materialized: view
    marts:
      +materialized: table
